'use client';

import { createContext, useContext } from 'react';

export type Language = 'pl' | 'en' | 'de';

export const translations = {
  pl: {
    // Header
    features: 'Funkcje',
    specifications: 'Specyfikacje',
    order: 'Zamów',
    orderNow: 'Zamów teraz',
    
    // Country detection
    countryDetected: 'Wykryto kraj',
    languageSetAutomatically: '(język ustawiony automatycznie)',
    
    // Hero
    heroTitle: 'Inteligentny Sen',
    heroTitleHighlight: '',
    heroDescription: 'Zaawansowane monitorowanie zdrowia w eleganckim pierścieniu. Śledź sen, aktywność i parametry życiowe 24/7 dzięki najnowocześniejszej technologii.',
    orderNowPrice: 'Zamów teraz – 99€',
    
    // Features
    featuresTitle: 'Wszystko, czego potrzebujesz w jednym pierścieniu',
    featuresIntro: 'Smart Ring łączy w sobie zaawansowane technologie monitorowania zdrowia w eleganckim, dyskretnym urządzeniu, które nosisz 24/7.',
    sleepMonitoring: 'Monitoring snu',
    sleepDescription: 'Śledź głęboki sen i fazy REM, budź się w najlepszym momencie.',
    activityMonitoring: 'Aktywność fizyczna',
    activityDescription: 'Monitoruj kroki, kalorie i treningi. Ustalaj cele i trzymaj formę.',
    temperatureMonitoring: 'Temperatura ciała',
    temperatureDescription: 'Subtelne zmiany temperatury pomogą wcześniej wykryć obciążenie organizmu.',
    heartRate: 'Tętno',
    heartRateDescription: 'Precyzyjne pomiary spoczynkowe i podczas wysiłku, 24/7.',
    
    // Stats
    statsTitle: 'Specyfikacje techniczne',
    batteryLife: 'dni pracy baterii',
    measurementAccuracy: 'precyzja pomiarów',
    monitoring: 'monitorowanie',
    waterResistance: 'wodoodporność',
    
    // Gallery
    galleryTitle: 'Galeria produktu',
    colorVariants: 'Warianty kolorystyczne',
    closeUps: 'Zbliżenia',
    colorBlack: 'Czarny',
    colorSilver: 'Srebrny',
    colorGold: 'Złoty',
    
    // Order
    orderTitle: 'Zamów już dziś Smart Ring',
    orderSubtitle: 'Dołącz do tysięcy zadowolonych użytkowników Smart Ring',
    price: '99€',
    freeShipping: 'Darmowa dostawa',
    returnPolicy: '30 dni na zwrot',
    warranty: '2 lata gwarancji',
    orderAdditionalInfo: '🔒 Bezpieczna płatność • 📱 Kompatybilne z iOS i Android',

    // Details
    detailsTitle: 'Szczegółowy opis',
    detailsParagraph: '',
    detailSleepTitle: 'Sen i regeneracja',
    detailSleepDesc: 'Analiza faz snu (REM, głęboki), wskazówki poprawy energii.',
    detailActivityTitle: 'Aktywność i sport',
    detailActivityDesc: 'Kroki, kalorie, dystans i tryby sportowe; cele tygodniowe.',
    detailHRVTitle: 'Tętno i HRV',
    detailHRVDesc: 'Całodobowe pomiary HR/HRV i stresu dla pełnego obrazu zdrowia.',
    detailBatteryTitle: 'Długa praca',
    detailBatteryDesc: 'Bateria 5–7 dni, ładowanie w magnetycznym etui ~1,5 h.',
    detailsGainsTitle: 'Co zyskujesz',
    detailsGain1: 'Wgląd w sen, aktywność, temperaturę skóry, tętno i SpO₂ w jednym miejscu.',
    detailsGain2: 'Subtelne wskazówki oparte na trendach — bez rozpraszających ekranów.',
    detailsGain3: '5–7 dni pracy na baterii i szybkie ładowanie w magnetycznym etui.',
    detailsGain4: 'Wygodę i styl — lekka konstrukcja, wodoodporność 5 ATM.',
    detailsCompatibility: 'Kompatybilność: Android 5.1+ / iOS 8.0+ • Aplikacja: QRing • Bluetooth 5.2',
    
    // Extended Product Description
    extendedHeroTitle: 'Inteligentny Sen. Śledź, mierz i poprawiaj jakość swojego snu noc po nocy. Zacznij już dziś.',
    extendedHeroSubtitle: '',
    healthIntelligenceTitle: 'INTELIGENCJA ZDROWOTNA, KTÓRA NIGDY NIE ŚPI',
    healthIntelligenceDesc: 'Nasz inteligentny pierścień nieustannie monitoruje sygnały Twojego ciała, dostarczając spersonalizowane wskazówki w celu poprawy zdrowia i wydajności.',
    coreFeaturesTitle: 'GŁÓWNE FUNKCJE:',
    sleepMonitoringExtended: 'Monitoring snu',
    sleepMonitoringExtendedDesc: 'Szczegółowa analiza faz snu, wzorców i spersonalizowane wskazówki dla lepszej regeneracji',
    heartHealthTitle: 'Zdrowie serca',
    heartHealthDesc: 'Ciągłe monitorowanie tętna, analiza HRV i spersonalizowane alerty zdrowotne',
    activityTrackingTitle: 'Śledzenie aktywności',
    activityTrackingDesc: 'Automatyczne wykrywanie treningów, liczenie kroków i szacowanie spalonych kalorii',
    modernLifeTitle: 'ZAPROJEKTOWANY DLA NOWOCZESNEGO ŻYCIA',
    noRecurringCostsTitle: 'Brak kosztów abonamentowych',
    noRecurringCostsDesc: 'W porównaniu do innych inteligentnych pierścieni i trackerów zdrowia na rynku, takich jak Oura™ i Whoop™, nie ma miesięcznych opłat abonamentowych za korzystanie z aplikacji. Wszystkie funkcje są bezpłatne na zawsze - zapłać raz i ciesz się wszystkimi funkcjami przez całe życie.',
    noRecurringCostsBenefits: '• Brak miesięcznych opłat za aplikację\n• Wszystkie funkcje premium w zestawie\n• Dożywotni dostęp do aktualizacji',
    ultraLightweightTitle: 'Ultralekkia konstrukcja',
    ultraLightweightDesc: 'Przy wadze poniżej 4 gramów, nasz inteligentny pierścień został zaprojektowany tak, aby zapomnieć o nim po założeniu. Bezszwowa, dyskretna konstrukcja wtapia się w Twoje codzienne życie bez rozpraszania.',
    ultraLightweightBenefits: '• Wygodny do noszenia 24/7\n• Wytrzymała konstrukcja z tytanu\n• Wodoodporny do 100m',
    batteryLifeExtendedTitle: '7+ dni pracy baterii',
    batteryLifeExtendedDesc: 'Nasza zaawansowana technologia optymalizacji energii zapewnia, że Twój inteligentny pierścień działa przez cały tydzień na jednym ładowaniu. Wygodna stacja ładowania bezprzewodowego ładuje pierścień w zaledwie 80 minut.',
    batteryLifeExtendedBenefits: '• Szybkie ładowanie bezprzewodowe\n• Energooszczędne czujniki\n• Zarządzanie zdrowiem baterii',
    precisionSensorsTitle: 'Precyzyjne czujniki',
    precisionSensorsDesc: 'Nasz inteligentny pierścień zawiera wiele wysokoprecyzyjnych czujników w swojej małej obudowie, przechwytując tysiące punktów danych na sekundę, aby dostarczyć dokładne wskaźniki zdrowia.',
    precisionSensorsBenefits: '• Czujniki PPG klasy medycznej\n• Akcelerometr 3D\n• Monitorowanie temperatury',
    healthInsightsTitle: 'WSKAZÓWKI ZDROWOTNE, KTÓRE MAJĄ ZNACZENIE',
    healthInsightsDesc: 'Przekształć swoje zdrowie dzięki spersonalizowanym wskazówkom i wskaźnikom, które pomagają lepiej zrozumieć swoje ciało.',
    sleepAnalysisTitle: 'Analiza snu',
    sleepAnalysisDesc: 'Śledź fazy snu (REM, głęboki sen, lekki sen), czas trwania i jakość. Otrzymuj spersonalizowane rekomendacje w celu poprawy higieny snu.',
    heartHealthAnalysisTitle: 'Zdrowie serca',
    heartHealthAnalysisDesc: 'Monitoruj spoczynkowe tętno, zmienność rytmu serca (HRV) i otrzymuj alerty o nieregularnych rytmach lub wzorcach.',
    activityMonitoringAnalysisTitle: 'Monitorowanie aktywności',
    activityMonitoringAnalysisDesc: 'Śledź kroki, szacuj spalone kalorie i automatycznie wykrywaj różne rodzaje treningów dla pełnego obrazu Twojej aktywności.',
    temperatureInsightsTitle: 'Wskazówki temperaturowe',
    temperatureInsightsDesc: 'Monitoruj trendy temperatury ciała, aby wykryć wczesne oznaki choroby, śledzić cykle menstruacyjne lub identyfikować wzorce regeneracji.',
    stressManagementTitle: 'Zarządzanie stresem',
    stressManagementDesc: 'Zrozumienie poziomu stresu w ciągu dnia pomaga zidentyfikować wyzwalacze i opracować lepsze strategie radzenia sobie.',
    dailyReportsTitle: 'Raporty dzienne',
    dailyReportsDesc: 'Otrzymuj kompleksowe dzienne podsumowania zdrowia z praktycznymi wskazówkami i rekomendacjami dostosowanymi do Twoich celów.',
    technicalSpecsTitle: 'SPECYFIKACJE TECHNICZNE',
    technicalSpecsModel: 'Model: Smart Ring',
    technicalSpecsConnectivity: 'Łączność: Bluetooth 5.2',
    technicalSpecsWeight: 'Waga: 4-6g (w zależności od rozmiaru)',
    technicalSpecsBattery: 'Bateria: Do 7 dni pracy baterii',
    technicalSpecsCharging: 'Ładowanie: Etui ładujące w zestawie',
    technicalSpecsWaterResistance: 'Wodoodporność: 5ATM wodoodporny',
    technicalSpecsSensors: 'Czujniki: Monitor tętna, tlen we krwi, czujnik temperatury',
    technicalSpecsCompatibility: 'Kompatybilność: iOS i Android',
    technicalSpecsWarranty: 'Gwarancja: 1 rok ograniczonej gwarancji',
    availableOptionsTitle: 'Dostępne opcje:',
    availableOptionsSizes: '• Rozmiary: Dostępne w rozmiarach 8-12',
    availableOptionsColors: '• Kolory: Czarny, Złoty, Srebrny',
    productBenefitsTitle: 'KORZYŚCI PRODUKTU',
    productBenefitsList: '• Brak kosztów abonamentowych (w porównaniu do innych inteligentnych pierścieni i trackerów zdrowia jak Oura™ i Whoop™)\n• 7+ dni pracy baterii\n• Zaawansowane monitorowanie snu\n• Śledzenie aktywności\n• Analiza tętna i HRV\n• Darmowa dostawa na cały świat',
    priceTitle: 'CENA: 99€',
    shippingInfo: 'Wysyłka w ciągu 24 godzin',
    readyToTransformTitle: 'GOTOWY NA TRANSFORMACJĘ ZDROWIA?',
    readyToTransformDesc: 'Dołącz do tysięcy użytkowników przejmujących kontrolę nad swoim zdrowiem dzięki najbardziej zaawansowanej technologii inteligentnych pierścieni dostępnej na rynku.',
    
    // Footer
    quickLinks: 'Szybkie linki',
    socialMedia: 'Social Media',
    footerDescription: 'Nowoczesne rozwiązania do monitorowania zdrowia i snu',
    copyright: ' 2024 Smart Ring. Wszystkie prawa zastrzeżone.'
  },
  en: {
    // Header
    features: 'Features',
    specifications: 'Specifications',
    order: 'Order',
    orderNow: 'Order Now',
    
    // Country detection
    countryDetected: 'Country detected',
    languageSetAutomatically: '(language set automatically)',
    
    // Hero
    heroTitle: 'Smart Sleep',
    heroTitleHighlight: '',
    heroDescription: 'Advanced health monitoring in an elegant ring. Track sleep, activity, and vital signs 24/7 with cutting-edge technology.',
    orderNowPrice: 'Order now – €99',
    
    // Features
    featuresTitle: 'Everything you need in one ring',
    featuresIntro: 'Smart Ring combines advanced health monitoring technologies in an elegant, discreet device you wear 24/7.',
    sleepMonitoring: 'Sleep Monitoring',
    sleepDescription: 'Track deep sleep and REM; wake up at the right moment.',
    activityMonitoring: 'Physical Activity',
    activityDescription: 'Track steps, calories and workouts. Set goals and stay on track.',
    temperatureMonitoring: 'Body Temperature',
    temperatureDescription: 'Subtle temperature trends help detect strain early.',
    heartRate: 'Heart Rate',
    heartRateDescription: 'Accurate resting and workout heart rate, 24/7.',
    
    // Stats
    statsTitle: 'Technical specifications',
    batteryLife: 'days battery life',
    measurementAccuracy: 'measurement accuracy',
    monitoring: 'monitoring',
    waterResistance: 'water resistance',
    
    // Gallery
    galleryTitle: 'Product Gallery',
    colorVariants: 'Color Variants',
    closeUps: 'Close-ups',
    colorBlack: 'Black',
    colorSilver: 'Silver',
    colorGold: 'Gold',
    
    // Order
    orderTitle: 'Order Smart Ring Today',
    orderSubtitle: 'Join thousands of happy Smart Ring users',
    price: '€99',
    freeShipping: 'Free shipping',
    returnPolicy: '30-day return',
    warranty: '2-year warranty',
    orderAdditionalInfo: '🔒 Secure payment • 📱 Compatible with iOS and Android',

    // Details
    detailsTitle: 'Detailed description',
    detailsParagraph: '',
    detailSleepTitle: 'Sleep and recovery',
    detailSleepDesc: 'Sleep stage analysis (REM, deep), tips to improve energy.',
    detailActivityTitle: 'Activity and sport',
    detailActivityDesc: 'Steps, calories, distance and sport modes; weekly goals.',
    detailHRVTitle: 'Heart rate and HRV',
    detailHRVDesc: '24/7 HR/HRV and stress measurements for a complete health picture.',
    detailBatteryTitle: 'Long battery life',
    detailBatteryDesc: 'Battery 5–7 days, charging in magnetic case ~1.5 h.',
    detailsGainsTitle: 'What you get',
    detailsGain1: 'Insights into sleep, activity, skin temperature, heart rate and SpO₂ in one place.',
    detailsGain2: 'Subtle, trend-based guidance — without distracting screens.',
    detailsGain3: '5–7 days battery life and fast charging in a magnetic case.',
    detailsGain4: 'Comfort and style — lightweight build, 5 ATM water resistance.',
    detailsCompatibility: 'Compatibility: Android 5.1+ / iOS 8.0+ • App: QRing • Bluetooth 5.2',
    
    // Extended Product Description
    extendedHeroTitle: 'Smart Sleep. Track, measure and improve your sleep quality night after night. Start today.',
    extendedHeroSubtitle: '',
    healthIntelligenceTitle: 'HEALTH INTELLIGENCE THAT NEVER SLEEPS',
    healthIntelligenceDesc: 'Our smart ring continuously monitors your body\'s signals, providing personalized insights to improve your health and performance.',
    coreFeaturesTitle: 'CORE FEATURES:',
    sleepMonitoringExtended: 'Sleep Monitoring',
    sleepMonitoringExtendedDesc: 'Detailed sleep stage analysis, patterns, and personalized guidance for better recovery',
    heartHealthTitle: 'Heart Health',
    heartHealthDesc: 'Continuous heart rate monitoring, HRV analysis, and personalized health alerts',
    activityTrackingTitle: 'Activity Tracking',
    activityTrackingDesc: 'Automatic workout detection, step counting, and calorie burn estimation',
    modernLifeTitle: 'DESIGNED FOR MODERN LIFE',
    noRecurringCostsTitle: 'No Recurring Costs',
    noRecurringCostsDesc: 'Compared to other smart rings and health trackers on the market like Oura™ and Whoop™, there are no monthly subscription fees for using the app. All functions are permanently free - pay once and enjoy all features for life.',
    noRecurringCostsBenefits: '• No monthly app fees\n• All premium features included\n• Lifetime access to updates',
    ultraLightweightTitle: 'Ultra-Lightweight Design',
    ultraLightweightDesc: 'At less than 4 grams, our smart ring is designed to be forgotten once you put it on. The seamless, unobtrusive design blends into your daily life without distraction.',
    ultraLightweightBenefits: '• Comfortable for 24/7 wear\n• Durable titanium construction\n• Waterproof up to 100m',
    batteryLifeExtendedTitle: '7+ Days Battery Life',
    batteryLifeExtendedDesc: 'Our advanced power optimization technology ensures your smart ring works for an entire week on a single charge. The convenient wireless charging station charges the ring in just 80 minutes.',
    batteryLifeExtendedBenefits: '• Fast wireless charging\n• Power-efficient sensors\n• Battery health management',
    precisionSensorsTitle: 'Precision Sensors',
    precisionSensorsDesc: 'Our smart ring packs multiple high-precision sensors into its tiny frame, capturing thousands of data points per second to deliver accurate health metrics.',
    precisionSensorsBenefits: '• Medical-grade PPG sensors\n• 3D accelerometer\n• Temperature monitoring',
    healthInsightsTitle: 'HEALTH INSIGHTS THAT MATTER',
    healthInsightsDesc: 'Transform your health with personalized insights and metrics that help you better understand your body.',
    sleepAnalysisTitle: 'Sleep Analysis',
    sleepAnalysisDesc: 'Track your sleep stages (REM, deep sleep, light sleep), duration, and quality. Get personalized recommendations to improve your sleep hygiene.',
    heartHealthAnalysisTitle: 'Heart Health',
    heartHealthAnalysisDesc: 'Monitor your resting heart rate, heart rate variability (HRV), and receive alerts for irregular rhythms or patterns.',
    activityMonitoringAnalysisTitle: 'Activity Monitoring',
    activityMonitoringAnalysisDesc: 'Track steps, estimate calories burned, and automatically detect various workout types for a complete picture of your activity.',
    temperatureInsightsTitle: 'Temperature Insights',
    temperatureInsightsDesc: 'Monitor your body temperature trends to detect early signs of illness, track menstrual cycles, or identify recovery patterns.',
    stressManagementTitle: 'Stress Management',
    stressManagementDesc: 'Understanding your stress levels throughout the day helps you identify triggers and develop better coping strategies.',
    dailyReportsTitle: 'Daily Reports',
    dailyReportsDesc: 'Receive comprehensive daily health summaries with actionable insights and recommendations tailored to your goals.',
    technicalSpecsTitle: 'TECHNICAL SPECIFICATIONS',
    technicalSpecsModel: 'Model: Smart Ring',
    technicalSpecsConnectivity: 'Connectivity: Bluetooth 5.2',
    technicalSpecsWeight: 'Weight: 4-6g (depending on size)',
    technicalSpecsBattery: 'Battery: Up to 7 days battery life',
    technicalSpecsCharging: 'Charging: Charging case included',
    technicalSpecsWaterResistance: 'Water Resistance: 5ATM waterproof',
    technicalSpecsSensors: 'Sensors: Heart rate monitor, blood oxygen, temperature sensor',
    technicalSpecsCompatibility: 'Compatibility: iOS and Android',
    technicalSpecsWarranty: 'Warranty: 1 year limited warranty',
    availableOptionsTitle: 'Available Options:',
    availableOptionsSizes: '• Sizes: Available in sizes 8-12',
    availableOptionsColors: '• Colors: Black, Gold, Silver',
    productBenefitsTitle: 'PRODUCT BENEFITS',
    productBenefitsList: '• No recurring app costs (compared to other smart rings and health trackers like Oura™ and Whoop™)\n• 7+ days battery life\n• Advanced sleep monitoring\n• Activity tracking\n• Heart rate & HRV analysis\n• Free worldwide shipping',
    priceTitle: 'PRICE: $299',
    shippingInfo: 'Ships within 24 hours',
    readyToTransformTitle: 'READY TO TRANSFORM YOUR HEALTH?',
    readyToTransformDesc: 'Join thousands of users taking control of their health with the most advanced smart ring technology available.',
    
    // Footer
    quickLinks: 'Quick links',
    socialMedia: 'Social Media',
    footerDescription: 'Modern solutions for health and sleep monitoring',
    copyright: '© 2024 Smart Ring. All rights reserved.'
  },
  de: {
    // Header
    features: 'Funktionen',
    specifications: 'Spezifikationen',
    order: 'Bestellen',
    orderNow: 'Jetzt bestellen',
    
    // Country detection
    countryDetected: 'Land erkannt',
    languageSetAutomatically: '(Sprache automatisch eingestellt)',
    
    // Hero
    heroTitle: 'Intelligenter Schlafen',
    heroTitleHighlight: '',
    heroDescription: 'Fortschrittliche Gesundheitsüberwachung in einem eleganten Ring. Verfolgen Sie Schlaf, Aktivität und Vitalwerte 24/7 mit modernster Technologie.',
    orderNowPrice: 'Jetzt bestellen – 99€',
    
    // Features
    featuresTitle: 'Alles was Sie brauchen in einem Ring',
    featuresIntro: 'Smart Ring vereint fortschrittliche Gesundheitsüberwachung in einem eleganten, dezenten Gerät, das Sie 24/7 tragen.',
    sleepMonitoring: 'Schlafüberwachung',
    sleepDescription: 'Verfolge Tiefschlaf und REM‑Phasen, wache im richtigen Moment auf.',
    activityMonitoring: 'Körperliche Aktivität',
    activityDescription: 'Schritte, Kalorien und Workouts im Blick. Ziele setzen und dranbleiben.',
    temperatureMonitoring: 'Körpertemperatur',
    temperatureDescription: 'Feine Temperaturtrends helfen, Belastung früh zu erkennen.',
    heartRate: 'Herzfrequenz',
    heartRateDescription: 'Präzise Ruhe‑ und Trainings‑Herzfrequenz, 24/7.',
    
    // Stats
    statsTitle: 'Technische Spezifikationen',
    batteryLife: 'Tage Akkulaufzeit',
    measurementAccuracy: 'Messgenauigkeit',
    monitoring: 'Überwachung',
    waterResistance: 'Wasserfestigkeit',
    
    // Gallery
    galleryTitle: 'Produktgalerie',
    colorVariants: 'Farbvarianten',
    closeUps: 'Nahaufnahmen',
    colorBlack: 'Schwarz',
    colorSilver: 'Silber',
    colorGold: 'Gold',
    
    // Order
    orderTitle: 'Bestellen Sie Smart Ring heute',
    orderSubtitle: 'Schließen Sie sich tausenden zufriedenen Smart‑Ring‑Nutzern an',
    price: '99€',
    freeShipping: 'Kostenloser Versand',
    returnPolicy: '30 Tage Rückgabe',
    warranty: '2 Jahre Garantie',
    orderAdditionalInfo: '🔒 Sichere Zahlung • 📱 Kompatibel mit iOS und Android',

    // Details
    detailsTitle: 'Detaillierte Beschreibung',
    detailsParagraph: '',
    detailSleepTitle: 'Schlaf und Regeneration',
    detailSleepDesc: 'Analyse der Schlafphasen (REM, Tiefschlaf), Tipps für mehr Energie.',
    detailActivityTitle: 'Aktivität und Sport',
    detailActivityDesc: 'Schritte, Kalorien, Distanz und Sportmodi; wöchentliche Ziele.',
    detailHRVTitle: 'Herzfrequenz und HRV',
    detailHRVDesc: '24/7 HR/HRV- und Stressmessungen für ein vollständiges Gesundheitsbild.',
    detailBatteryTitle: 'Lange Laufzeit',
    detailBatteryDesc: 'Akku 5–7 Tage, Laden im magnetischen Etui ~1,5 Std.',
    detailsGainsTitle: 'Ihre Vorteile',
    detailsGain1: 'Einblicke in Schlaf, Aktivität, Hauttemperatur, Herzfrequenz und SpO₂ an einem Ort.',
    detailsGain2: 'Feine, trendbasierte Hinweise — ohne ablenkende Bildschirme.',
    detailsGain3: '5–7 Tage Akkulaufzeit und schnelles Laden im magnetischen Etui.',
    detailsGain4: 'Komfort und Stil — leichtes Design, 5 ATM Wasserfestigkeit.',
    detailsCompatibility: 'Kompatibilität: Android 5.1+ / iOS 8.0+ • App: QRing • Bluetooth 5.2',
    
    // Extended Product Description
    extendedHeroTitle: 'Intelligenter Schlafen. Verfolgen, messen und verbessern Sie Ihre Schlafqualität Nacht für Nacht. Starten Sie heute.',
    extendedHeroSubtitle: '',
    healthIntelligenceTitle: 'GESUNDHEITSINTELLIGENZ, DIE NIEMALS SCHLÄFT',
    healthIntelligenceDesc: 'Unser intelligenter Ring überwacht kontinuierlich die Signale Ihres Körpers und liefert personalisierte Erkenntnisse zur Verbesserung Ihrer Gesundheit und Leistung.',
    coreFeaturesTitle: 'KERNFUNKTIONEN:',
    sleepMonitoringExtended: 'Schlafüberwachung',
    sleepMonitoringExtendedDesc: 'Detaillierte Schlafphasenanalyse, Muster und personalisierte Anleitung für bessere Erholung',
    heartHealthTitle: 'Herzgesundheit',
    heartHealthDesc: 'Kontinuierliche Herzfrequenzüberwachung, HRV-Analyse und personalisierte Gesundheitswarnungen',
    activityTrackingTitle: 'Aktivitätsverfolgung',
    activityTrackingDesc: 'Automatische Trainingserkennung, Schrittzählung und Kalorienverbrauchsschätzung',
    modernLifeTitle: 'FÜR DAS MODERNE LEBEN ENTWICKELT',
    noRecurringCostsTitle: 'Keine wiederkehrenden Kosten',
    noRecurringCostsDesc: 'Im Vergleich zu anderen intelligenten Ringen und Gesundheitstrackern auf dem Markt wie Oura™ und Whoop™ gibt es keine monatlichen Abonnementgebühren für die Nutzung der App. Alle Funktionen sind dauerhaft kostenlos - einmal zahlen und alle Funktionen lebenslang genießen.',
    noRecurringCostsBenefits: '• Keine monatlichen App-Gebühren\n• Alle Premium-Funktionen enthalten\n• Lebenslanger Zugang zu Updates',
    ultraLightweightTitle: 'Ultraleichtes Design',
    ultraLightweightDesc: 'Mit weniger als 4 Gramm ist unser intelligenter Ring so konzipiert, dass Sie ihn vergessen, sobald Sie ihn aufsetzen. Das nahtlose, unauffällige Design fügt sich ohne Ablenkung in Ihr tägliches Leben ein.',
    ultraLightweightBenefits: '• Bequem für 24/7-Tragen\n• Langlebige Titan-Konstruktion\n• Wasserdicht bis 100m',
    batteryLifeExtendedTitle: '7+ Tage Akkulaufzeit',
    batteryLifeExtendedDesc: 'Unsere fortschrittliche Energieoptimierungstechnologie sorgt dafür, dass Ihr intelligenter Ring eine ganze Woche mit einer einzigen Ladung funktioniert. Die praktische kabellose Ladestation lädt den Ring in nur 80 Minuten.',
    batteryLifeExtendedBenefits: '• Schnelles kabelloses Laden\n• Energieeffiziente Sensoren\n• Batteriegesundheitsmanagement',
    precisionSensorsTitle: 'Präzisionssensoren',
    precisionSensorsDesc: 'Unser intelligenter Ring packt mehrere hochpräzise Sensoren in seinen winzigen Rahmen und erfasst Tausende von Datenpunkten pro Sekunde, um genaue Gesundheitsmetriken zu liefern.',
    precisionSensorsBenefits: '• Medizinische PPG-Sensoren\n• 3D-Beschleunigungsmesser\n• Temperaturüberwachung',
    healthInsightsTitle: 'GESUNDHEITSERKENNTNISSE, DIE WICHTIG SIND',
    healthInsightsDesc: 'Transformieren Sie Ihre Gesundheit mit personalisierten Erkenntnissen und Metriken, die Ihnen helfen, Ihren Körper besser zu verstehen.',
    sleepAnalysisTitle: 'Schlafanalyse',
    sleepAnalysisDesc: 'Verfolgen Sie Ihre Schlafphasen (REM, Tiefschlaf, Leichtschlaf), Dauer und Qualität. Erhalten Sie personalisierte Empfehlungen zur Verbesserung Ihrer Schlafhygiene.',
    heartHealthAnalysisTitle: 'Herzgesundheit',
    heartHealthAnalysisDesc: 'Überwachen Sie Ihre Ruheherzfrequenz, Herzfrequenzvariabilität (HRV) und erhalten Sie Warnungen bei unregelmäßigen Rhythmen oder Mustern.',
    activityMonitoringAnalysisTitle: 'Aktivitätsüberwachung',
    activityMonitoringAnalysisDesc: 'Verfolgen Sie Schritte, schätzen Sie verbrannte Kalorien und erkennen Sie automatisch verschiedene Trainingsarten für ein vollständiges Bild Ihrer Aktivität.',
    temperatureInsightsTitle: 'Temperaturerkenntnisse',
    temperatureInsightsDesc: 'Überwachen Sie Ihre Körpertemperaturtrends, um frühe Anzeichen von Krankheiten zu erkennen, Menstruationszyklen zu verfolgen oder Erholungsmuster zu identifizieren.',
    stressManagementTitle: 'Stressmanagement',
    stressManagementDesc: 'Das Verständnis Ihrer Stresslevel während des Tages hilft Ihnen, Auslöser zu identifizieren und bessere Bewältigungsstrategien zu entwickeln.',
    dailyReportsTitle: 'Tägliche Berichte',
    dailyReportsDesc: 'Erhalten Sie umfassende tägliche Gesundheitszusammenfassungen mit umsetzbaren Erkenntnissen und Empfehlungen, die auf Ihre Ziele zugeschnitten sind.',
    technicalSpecsTitle: 'TECHNISCHE SPEZIFIKATIONEN',
    technicalSpecsModel: 'Modell: Smart Ring',
    technicalSpecsConnectivity: 'Konnektivität: Bluetooth 5.2',
    technicalSpecsWeight: 'Gewicht: 4-6g (je nach Größe)',
    technicalSpecsBattery: 'Akku: Bis zu 7 Tage Akkulaufzeit',
    technicalSpecsCharging: 'Laden: Ladeetui enthalten',
    technicalSpecsWaterResistance: 'Wasserfestigkeit: 5ATM wasserdicht',
    technicalSpecsSensors: 'Sensoren: Herzfrequenzmesser, Blutsauerstoff, Temperatursensor',
    technicalSpecsCompatibility: 'Kompatibilität: iOS und Android',
    technicalSpecsWarranty: 'Garantie: 1 Jahr beschränkte Garantie',
    availableOptionsTitle: 'Verfügbare Optionen:',
    availableOptionsSizes: '• Größen: Verfügbar in den Größen 8-12',
    availableOptionsColors: '• Farben: Schwarz, Gold, Silber',
    productBenefitsTitle: 'PRODUKTVORTEILE',
    productBenefitsList: '• Keine wiederkehrenden App-Kosten (im Vergleich zu anderen intelligenten Ringen und Gesundheitstrackern wie Oura™ und Whoop™)\n• 7+ Tage Akkulaufzeit\n• Erweiterte Schlafüberwachung\n• Aktivitätsverfolgung\n• Herzfrequenz- und HRV-Analyse\n• Kostenloser weltweiter Versand',
    priceTitle: 'PREIS: 99€',
    shippingInfo: 'Versand innerhalb von 24 Stunden',
    readyToTransformTitle: 'BEREIT, IHRE GESUNDHEIT ZU TRANSFORMIEREN?',
    readyToTransformDesc: 'Schließen Sie sich Tausenden von Benutzern an, die mit der fortschrittlichsten verfügbaren intelligenten Ring-Technologie die Kontrolle über ihre Gesundheit übernehmen.',
    
    // Footer
    quickLinks: 'Schnelle Links',
    socialMedia: 'Soziale Medien',
    footerDescription: 'Moderne Lösungen für Gesundheits- und Schlafüberwachung',
    copyright: '© 2024 Smart Ring. Alle Rechte vorbehalten.'
  }
};

export type LanguageContextValue = {
  language: Language;
  changeLanguage: (newLanguage: Language) => void;
  t: (key: keyof typeof translations.pl) => string;
};

export const LanguageContext = createContext<LanguageContextValue>({
  language: 'pl',
  changeLanguage: () => {},
  t: (key) => translations.pl[key],
});

export function useLanguage() {
  return useContext(LanguageContext);
}